### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/webkit-tools#26]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] base_headers_webkit
- [ ] report_webkit_chapter_server
- [ ] report_webkit_barcode

**Comment by ovnicraft** [comment]
Dont forget barcode, i migrate it for 8.0 here: https://github.com/OCA/webkit-tools/pull/29

**Comment by pedrobaeza** [comment]
When the module is available at v8, I'll add it here.

**Comment by ovnicraft** [comment]
:+1:

**Comment by ovnicraft** [comment]
@pedrobaeza so #29 was merged can be added here :-)

**Comment by pedrobaeza** [comment]
@ovnicraft, done
